-- ============================================================
-- NO-OP intencional (2026-07-24) — migration abandonada
-- ============================================================
-- Esta migration tentava recriar usuario_subgrupo.funcao como NOT NULL com
-- valores em maiúsculo/acento ('Operação','Nível 1','Nível 2'). Mas a coluna
-- JÁ existia — criada em 20260606000008_plano_acao.sql como `text NULL` com
-- valores minúsculos ('operacao','nivel_1','nivel_2'), que é o que o código e
-- as políticas RLS usam de fato.
--
-- Em produção esta migration SEMPRE falhou ("column funcao already exists") e,
-- por rodar em transação, fez rollback total — ou seja, NUNCA teve efeito algum
-- (nem a coluna, nem o índice, nem o comentário). A versão minúscula é a
-- autoritativa. Neutralizada para o histórico replicar do zero de forma fiel ao
-- estado real de produção (a baseline em prod nunca reexecuta este arquivo).
select 1;
